"""Add email verification

Revision ID: 81361390806e
Revises: 
Create Date: 2026-09-06 13:08:50.502266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81361390806e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
